version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    docker:
      - image: cimg/node:12.20.0-browsers
        auth:
          username: burhancoulibaly
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - node/install-packages
      - run:
          name: "Install firebase tools"
          command: |
            sudo npm install -g firebase-tools
      - run:
          name: "Start firebase emulators and test"
          command: |
            npm test

workflows:
  Chat_From_Home_Test:
    jobs:
      - test
